### PR TITLE
Test

### PR DESCRIPTION
**Pull request by roger-rkd**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [ ] Extension 
- [x] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
-  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by jainaayush01 — CHANGES_REQUESTED** [review]
Hey, Please go through submission guidelines and Getting Started Guide before submitting a PR,
things missing in the readme: 
1. demo video, 
2. how to run or install it, 
3. No proper project structure, name of PR, name of Project

Please make sure your PR shows the work you have put in.

The deadline is near, do it asap to make it a valid submission. 
waiting to hear back from you.

Cheers

**Comment by roger-rkd** [comment]
Can I get a day more?

Thankful and Regards,
Rohit Kumar Dubey.

**Comment by sudhanshutiwari264** [comment]
@roger-rkd
We got the chance to interact with some of you and upon a majority request, the project submission (with all changes before merging) is extended till Jul 11, 11:59 PM (IST).
Hope this extra time benefits you as well in completing the challenge with a blog/demo video by Jul 11, 11:59 PM (IST).

**Comment by jainaayush01** [comment]
any updates?
The deadline has passed

**Comment by roger-rkd** [comment]
very sorry, couldn't complete it due to my academic exams!
*Thanks and Regards,*
*Rohit Kumar Dubey*

(+91) 9453273003 <+919453273003> | ***@***.***
Gorakhnath, Gorakhpur
<http://www.facebook.com/roger.fc.14/>
<http://www.instagram.com/roger.innn/>
<http://www.linkedin.com/in/rohitkrdubey/>

**Comment by archithdwij** [comment]
Thank you for trying @roger-rkd You can submit your PR if you could so that we can at least check out  what you have worked on😃. It's contribution to the open source after all :)

**Comment by roger-rkd** [comment]
*Here's the link
<https://roger-in.medium.com/a-python-chatbot-ae48f9d37e16>*
*Thanks and Regards,*
*Rohit Kumar Dubey*

(+91) 9453273003 <+919453273003> | ***@***.***
Gorakhnath, Gorakhpur
<http://www.facebook.com/roger.fc.14/>
<http://www.instagram.com/roger.innn/>
<http://www.linkedin.com/in/rohitkrdubey/>

**Pull request closed without merging**
